### ISSUE TITLE
f string unclosed bracket, change inner quotation marks

### ISSUE THREAD

**Issue by briley173** [gergamel/binar_rcvr#1]
Line 121 of binar.py need to change inner quotation marks to singular, inner quotes were closing the f string.

Before
```python
name = f"{timestamp.strftime("%Y%m%d%H%M%S")}_{samplerate:.0f}_{dtype}"
```

After
```python
name = f"{timestamp.strftime('%Y%m%d%H%M%S')}_{samplerate:.0f}_{dtype}"
```

**Comment by gergamel** [comment]
Today I learned about [PEP 701](https://peps.python.org/pep-0701/), which is the reason this works on my machine (I'm using Python 3.12).

I will push a fix, but would like to find a way to disable this PEP as it probably keep happening while some people are still on <3.12...
